### ISSUE TITLE
Can I use two or more adapters in a component?

### ISSUE THREAD

**Issue by festelo** [alibaba/fish-redux#142]
For example, if I have 2 independent listview in a single component.

**Comment by zjuwjf** [comment]
Using two or more adapters in a component is very rare, and that's why a [Dependencies](https://github.com/alibaba/fish-redux/blob/master/doc/concept/dependencies.md) may have multiple slots but only one adapter. 

In your case，you could have two or more list-view components as slots in a single component.

**Comment by festelo** [comment]
Yes, I know that we can create own components for  2nd, 3rd and others list-view, but as for me, only one adapter restrictment looks strange. But if this case is really rare, we can close issue. Thank you.
